### ISSUE TITLE
Support for multiple drawer-trigger blocks scattered around a page

### ISSUE THREAD

**Issue by lucasecdb** [vtex-apps/store-discussion#246]
#### Is your feature request related to a problem? Please describe.
No, it's a pure feature request.

#### Describe the solution you'd like
I want to be able to have two blocks that can trigger the drawer to open, that should not be tied to the same location in the blocks tree. See the following image for a better visualization on this.

<img src="https://user-images.githubusercontent.com/10223856/77582791-b653ac80-6ebe-11ea-8ffb-6fedc3a14098.png" height="700">

The button "View Cart" in the header of the page should open a drawer showing the user's cart. Additionally, the button "See Cart" (in blue) should open _the same drawer_ as the button on the title.

#### Describe alternatives you've considered
Adding two `"drawer"` blocks, that have the same children block, but different `"drawer-trigger"` blocks. This isn't ideal, but works in simple scenarios when the children blocks are defined in the same app. In the case above, the "View Cart" block is rendered in a different app (`vtex.checkout`) than the "See Cart" (`vtex.checkout-payment`), so we would need a duplicate definition of the children.

#### Additional context
No additional context.

cc @davicosta99

**Comment by lucasecdb** [comment]
sorry if the template isn't the appropriate. I originally opened this issue in the vtex-apps/drawer repository and used the "Feature Request" template from there

**Comment by Klynger** [comment]
Done by https://github.com/vtex-apps/drawer/pull/15

**Comment by lucasecdb** [comment]
The linked feature does not solve this issue because what I wan't is to have _multiple_ drawer-trigger blocks in different parts of a page to open/close the _same_ drawer.

**Comment by kid-three** [comment]
Did you ever solve this?

**Comment by lucasecdb** [comment]
@kid-three no, I didn't.

**Comment by JoseMeneghetti** [comment]
Any progress about it guys?

**Comment by Klynger** [comment]
Is currently in progress @JoseMeneghetti
